name: B43-third-party-action-benign

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.TEST_SECRET }}"

      - name: Build
        run: |
          echo "building"
