name: N30-dns-benign-secret-unused

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - run: |
          echo "::add-mask::$API_KEY"
          nslookup github.com